---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    webservers:
      hosts:
        web.lab.local:
          ansible_host: 192.168.56.20

    services:
      hosts:
        services.lab.local:
          ansible_host: 192.168.56.30

    all_managed:
      children:
        webservers:
        services:
